//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medias
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Ext { get; set; }
        public long ExtID { get; set; }
        public string Path { get; set; }
        public string Type { get; set; }
        public long TypeID { get; set; }
    }
}
